import java.util.List;

class Day2 extends AocDay<List<Day2.Instruction>> {

    private static final String input = """
            forward 2
            down 4
            down 1
            down 4
            forward 3
            down 6
            down 5
            forward 3
            forward 8
            down 2
            down 3
            up 8
            down 5
            up 7
            down 7
            forward 5
            up 2
            down 6
            forward 7
            forward 1
            forward 2
            forward 7
            up 7
            forward 6
            down 3
            down 1
            up 9
            down 2
            up 1
            down 1
            up 6
            forward 6
            down 7
            forward 6
            up 1
            down 6
            forward 2
            up 7
            forward 4
            forward 8
            forward 7
            down 7
            forward 8
            down 1
            down 6
            down 7
            forward 4
            down 3
            up 7
            down 5
            down 9
            up 8
            up 4
            down 2
            down 3
            up 7
            forward 6
            forward 6
            forward 8
            forward 2
            up 5
            down 8
            down 3
            down 3
            down 4
            down 9
            down 6
            up 6
            forward 4
            down 6
            forward 3
            forward 3
            down 4
            down 8
            down 2
            up 5
            up 5
            forward 3
            forward 5
            down 7
            forward 6
            forward 9
            forward 8
            forward 2
            down 3
            down 3
            down 7
            down 1
            down 1
            down 1
            down 2
            down 8
            down 6
            forward 6
            up 1
            up 6
            down 7
            down 1
            forward 1
            up 2
            up 8
            up 8
            forward 2
            down 1
            down 8
            down 7
            down 1
            forward 1
            down 9
            up 3
            down 3
            forward 2
            down 3
            up 6
            down 2
            forward 7
            down 9
            down 6
            down 1
            forward 6
            down 4
            down 1
            down 3
            forward 3
            down 5
            forward 9
            down 5
            down 7
            up 8
            forward 8
            forward 8
            down 6
            down 1
            forward 8
            down 4
            up 4
            up 4
            up 2
            forward 2
            forward 2
            down 1
            up 8
            down 1
            down 7
            forward 5
            down 9
            down 2
            up 3
            down 1
            down 5
            forward 6
            down 7
            up 3
            forward 7
            down 4
            down 3
            forward 4
            up 8
            down 4
            forward 4
            forward 2
            forward 5
            down 5
            up 2
            forward 4
            down 4
            forward 6
            down 4
            forward 1
            down 5
            forward 2
            forward 2
            down 8
            forward 4
            forward 7
            down 3
            up 3
            forward 2
            forward 6
            forward 8
            down 2
            forward 4
            down 2
            up 9
            down 9
            down 2
            forward 5
            up 4
            forward 2
            down 2
            down 3
            forward 1
            down 2
            forward 8
            forward 8
            down 4
            forward 6
            down 3
            down 3
            down 5
            forward 8
            forward 4
            forward 1
            up 4
            up 2
            forward 8
            down 8
            forward 2
            forward 6
            up 1
            up 5
            forward 2
            forward 4
            forward 7
            forward 8
            forward 2
            down 3
            down 1
            down 9
            down 6
            up 5
            up 6
            forward 6
            down 3
            down 2
            down 1
            forward 5
            forward 2
            forward 7
            down 8
            down 7
            forward 7
            up 8
            forward 7
            down 1
            up 4
            forward 9
            forward 4
            forward 1
            down 3
            down 9
            down 7
            forward 1
            down 3
            forward 3
            down 4
            down 7
            forward 4
            up 6
            down 8
            up 1
            forward 6
            forward 1
            down 7
            down 8
            up 9
            up 4
            down 3
            down 7
            forward 8
            up 2
            up 6
            forward 8
            down 1
            up 4
            up 4
            forward 8
            down 2
            down 4
            down 3
            forward 5
            down 8
            forward 1
            down 2
            forward 9
            forward 3
            up 6
            down 6
            forward 6
            forward 4
            down 6
            down 3
            down 3
            forward 6
            down 5
            up 4
            down 9
            down 3
            down 6
            up 9
            forward 6
            down 2
            forward 7
            up 8
            down 3
            down 7
            down 9
            forward 6
            down 1
            forward 2
            down 1
            down 3
            down 3
            forward 5
            forward 2
            up 5
            forward 4
            up 7
            down 9
            forward 7
            forward 3
            down 6
            forward 1
            down 1
            up 8
            down 9
            up 3
            down 7
            up 9
            forward 7
            down 7
            down 9
            forward 9
            forward 7
            up 9
            down 7
            down 2
            down 7
            up 2
            down 3
            down 9
            down 6
            forward 7
            forward 8
            forward 8
            forward 6
            forward 9
            forward 4
            down 4
            down 5
            down 7
            forward 6
            forward 2
            forward 4
            forward 9
            down 4
            forward 6
            down 7
            up 1
            down 7
            forward 9
            forward 7
            down 4
            down 3
            up 6
            forward 8
            forward 7
            down 8
            forward 4
            up 6
            up 4
            forward 9
            forward 4
            forward 4
            forward 7
            down 1
            up 6
            forward 8
            forward 3
            up 6
            forward 4
            down 1
            up 2
            forward 1
            down 5
            forward 5
            up 4
            down 6
            down 3
            up 8
            forward 9
            down 2
            forward 4
            forward 8
            down 9
            forward 5
            forward 2
            down 9
            down 8
            forward 8
            down 7
            up 6
            forward 1
            up 9
            up 3
            forward 9
            down 6
            forward 9
            down 3
            down 3
            forward 7
            forward 5
            down 8
            down 9
            down 3
            down 6
            up 8
            down 9
            forward 8
            down 7
            down 5
            down 1
            up 4
            down 9
            forward 6
            forward 9
            up 6
            up 4
            forward 3
            forward 2
            forward 1
            down 1
            down 2
            forward 8
            up 6
            forward 5
            up 4
            down 1
            forward 5
            down 3
            down 6
            up 7
            forward 2
            forward 6
            forward 7
            forward 4
            down 5
            down 4
            forward 4
            down 6
            up 2
            up 2
            forward 7
            forward 3
            down 8
            down 1
            down 8
            forward 7
            forward 7
            up 5
            forward 4
            up 8
            down 9
            down 4
            down 4
            forward 5
            down 1
            forward 2
            down 6
            up 4
            down 8
            down 1
            down 9
            down 5
            up 5
            forward 4
            down 2
            down 8
            down 4
            forward 4
            forward 5
            down 8
            up 9
            forward 7
            forward 6
            down 8
            down 3
            up 7
            down 7
            forward 2
            forward 5
            forward 7
            down 9
            up 1
            down 6
            down 2
            forward 6
            forward 3
            forward 3
            up 9
            forward 4
            down 5
            down 7
            forward 8
            forward 6
            forward 5
            down 9
            down 5
            down 1
            down 7
            forward 9
            forward 8
            down 2
            down 4
            down 1
            up 5
            up 5
            forward 5
            down 3
            down 1
            forward 8
            up 9
            up 3
            down 3
            up 3
            up 5
            forward 8
            down 3
            up 3
            down 9
            up 6
            up 8
            forward 5
            up 2
            down 6
            forward 3
            down 2
            down 4
            forward 9
            forward 6
            forward 3
            up 5
            down 9
            down 7
            forward 9
            forward 7
            forward 5
            up 5
            up 1
            down 6
            forward 4
            forward 4
            down 7
            down 1
            up 3
            forward 6
            forward 4
            down 1
            forward 5
            forward 3
            forward 1
            forward 3
            up 3
            up 9
            down 7
            down 4
            forward 8
            down 8
            down 3
            up 2
            down 8
            forward 5
            down 7
            forward 6
            down 9
            up 5
            forward 4
            down 2
            forward 6
            down 8
            down 7
            forward 8
            forward 5
            down 2
            forward 7
            forward 5
            forward 7
            down 8
            forward 5
            down 8
            down 6
            down 7
            down 9
            forward 9
            down 6
            forward 8
            up 6
            up 1
            down 5
            forward 1
            forward 7
            up 2
            up 5
            up 6
            down 5
            down 5
            forward 7
            down 9
            down 2
            forward 9
            forward 3
            down 5
            up 2
            up 8
            forward 5
            forward 8
            up 1
            forward 3
            forward 1
            up 4
            forward 1
            down 9
            down 6
            forward 1
            down 4
            down 4
            forward 9
            down 3
            up 6
            down 3
            forward 6
            forward 6
            down 3
            forward 6
            down 3
            down 1
            forward 3
            down 7
            up 9
            forward 1
            down 7
            down 2
            up 8
            down 1
            down 9
            down 1
            down 4
            down 6
            down 3
            down 7
            down 2
            down 9
            down 2
            forward 4
            up 3
            down 4
            up 4
            down 1
            forward 5
            forward 7
            down 7
            forward 9
            forward 6
            down 8
            forward 6
            forward 7
            up 3
            down 3
            up 6
            forward 7
            up 4
            forward 4
            down 1
            up 8
            forward 7
            down 2
            up 6
            forward 1
            forward 3
            up 9
            up 8
            up 5
            forward 7
            up 5
            down 6
            forward 7
            forward 7
            down 4
            down 3
            forward 2
            down 8
            up 9
            up 6
            forward 7
            forward 5
            down 9
            down 2
            up 5
            down 3
            down 3
            up 5
            down 8
            forward 7
            down 4
            down 2
            up 9
            down 5
            down 8
            down 5
            down 6
            forward 9
            down 3
            down 8
            forward 3
            down 1
            down 9
            forward 1
            down 3
            up 9
            up 3
            forward 8
            up 2
            down 4
            up 5
            up 4
            down 9
            down 5
            up 3
            forward 2
            down 8
            forward 8
            forward 7
            up 4
            down 9
            down 6
            up 1
            forward 9
            up 8
            forward 4
            up 3
            down 4
            up 2
            up 7
            down 2
            forward 3
            down 8
            down 9
            up 7
            up 8
            forward 3
            forward 1
            forward 7
            forward 5
            forward 9
            forward 2
            up 1
            down 1
            up 4
            forward 1
            up 9
            forward 7
            forward 2
            down 6
            down 5
            forward 9
            forward 4
            down 6
            down 6
            up 8
            down 3
            up 8
            down 3
            forward 2
            down 1
            down 1
            forward 5
            down 1
            forward 9
            up 8
            forward 2
            down 5
            up 8
            up 8
            forward 8
            forward 8
            forward 3
            forward 2
            forward 8
            forward 9
            forward 8
            forward 6
            forward 4
            up 7
            forward 9
            forward 8
            up 7
            forward 6
            forward 9
            forward 8
            down 7
            forward 9
            down 4
            down 1
            up 1
            up 9
            forward 2
            down 6
            down 2
            down 8
            down 6
            up 8
            forward 7
            up 9
            forward 5
            forward 4
            forward 8
            up 4
            forward 4
            up 6
            forward 7
            forward 1
            up 8
            down 6
            forward 7
            forward 3
            forward 2
            down 4
            forward 4
            down 7
            down 6
            down 2
            up 3
            up 5
            down 7
            down 9
            up 8
            down 1
            up 1
            down 8
            up 8
            forward 8
            down 6
            down 1
            down 6
            forward 3
            down 9
            down 5
            up 3
            down 1
            down 1
            forward 4
            down 4
            up 3
            forward 8
            up 4
            down 3
            down 5
            down 3
            forward 6
            forward 3
            down 2
            forward 9
            forward 3
            forward 2
            down 2
            forward 6
            down 1
            down 1
            forward 5
            forward 4
            forward 6
            down 7
            forward 7
            forward 3
            forward 1
            up 3
            down 6
            forward 1
            up 9
            forward 9
            forward 5
            forward 3
            forward 3
            down 3
            up 8
            forward 5
            up 6
            forward 2
            down 7
            forward 2
            forward 8
            forward 8
            forward 3
            up 9
            down 5
            down 3
            forward 7
            up 9
            forward 4
            down 1
            down 3
            down 5
            down 2
            forward 9
            up 6
            down 3
            down 7
            down 3
            up 6
            forward 3
            down 4
            forward 2
            down 8
            down 2
            forward 7
            down 2
            down 9
            forward 1
            down 1
            down 9
            down 6
            forward 5
            down 1
            up 1
            forward 5
            forward 4
            forward 9
            down 3
            forward 3
            forward 5
            down 9
            forward 9
            down 8
            down 2
            forward 1
            up 1
            down 5
            forward 2
            up 9
            forward 9
            forward 7
            forward 9
            forward 3
            down 7
            forward 2
            down 4
            up 3
            down 7
            down 6
            forward 2
            down 2
            forward 8
            up 9
            down 1
            forward 7
            down 8
            forward 3
            down 2
            down 5
            down 5
            down 3
            forward 1
            up 9
            up 9
            down 8
            down 6
            up 7
            forward 7
            down 4
            forward 6
            down 9
            up 5
            up 6
            forward 4
            forward 1
            forward 1
            down 7
            down 8
            down 2
            down 4
            down 3
            up 8
            down 3
            forward 3
            forward 8
            up 3
            down 2
            forward 4
            down 3
            forward 5
            up 1
            down 9
            down 1
            down 4
            forward 3
            forward 6
            forward 7
            forward 2
            forward 9
            forward 1
            forward 6
            forward 7
            forward 2
            up 1
            down 6
            down 1
            forward 6
            down 6
            down 5
            forward 1
            """;

    public static void main(String[] args) {
        new Day2().solve(true, true);
    }

    @Override
    List<Instruction> prepareInput() {
        return input.lines()
                .map(line -> {
                    var parts = line.split(" ");
                    int amount = Integer.parseInt(parts[1]);
                    return new Instruction(parts[0], amount);
                })
                .toList();
    }

    @Override
    public String part1(List<Instruction> lines) {
        List<Move<Coordinate>> moves = lines.stream()
                .<Move<Coordinate>>map(instruction -> switch (instruction.direction()) {
                    case "forward" -> input -> input.withX(input.x() + instruction.amount());
                    case "down" -> input -> input.withY(input.y() + instruction.amount());
                    case "up" -> input -> input.withY(input.y() - instruction.amount());
                    default -> throw new IllegalArgumentException("Unsupported move " + instruction.direction());
                })
                .toList();
        var current = new Coordinate(0, 0);
        for (Move<Coordinate> move : moves) {
            current = move.apply(current);
        }
        return current.x() * current.y() + "";
    }

    @Override
    public String part2(List<Instruction> lines) {
        List<Move<Position>> moves = lines.stream()
                .<Move<Position>>map(instruction -> switch (instruction.direction()) {
                    case "forward" -> input -> new Position(input.x() + instruction.amount(), input.y() + (input.aim() * instruction.amount()), input.aim());
                    case "down" -> input -> new Position(input.x(), input.y(), input.aim() + instruction.amount());
                    case "up" -> input -> new Position(input.x(), input.y(), input.aim() - instruction.amount());
                    default -> throw new IllegalArgumentException("Unsupported move " + instruction.direction());
                })
                .toList();
        var current = new Position(0, 0, 0);
        for (Move<Position> move : moves) {
            current = move.apply(current);
        }
        return current.x() * current.y() + "";
    }

    interface Move<Input> {

        Input apply(Input input);

    }

    record Instruction(String direction, int amount) {}

    record Position(long x, long y, long aim) {}

}
